(define (fast-expt b n)
  (fast-expt-iter 1 b n)
)

(define (fast-expt-iter a b n)
  (cond ((= n 0) a)
        ((even? n)(fast-expt-iter a (* b b) (/ n 2)))
        (else (fast-expt-iter (* a b) b (- n 1)))
  )
)

(newline)
(display (fast-expt 2 0))(newline)
(display (fast-expt 2 10))(newline)
(display (fast-expt 2 32))(newline)
(display (fast-expt 2 64))(newline)
(display (fast-expt 3 3))(newline)
(display (fast-expt 3 10))(newline)
(display (fast-expt -5 3))(newline)