(define (smallest-divisor n)
  (find-divisor n 2)
)

(define (find-divisor n test-divisor)
  (cond ((> (square test-divisor) n) n)
        ((= 0 (remainder n test-divisor)) test-divisor)
        (else (find-divisor n (+ test-divisor 1)))
  )
)

(newline)
(display (smallest-divisor 199))(newline)
(display (smallest-divisor 1999))(newline)
(display (smallest-divisor 19999))(newline)
